version: "3.8"
services:
  db:
    image: "postgres:14"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
